/*
 * Copyright 2024-2026 GenCloud
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.genfork.grid.catalog;

import org.genfork.grid.mem.index.IndexType;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Set;

/**
 * Rebuilds compact {@code ddl.sql} lines from the live catalog (bootstrap compaction).
 *
 * @author: GenCloud
 * @date: 2026/09
 * @since: 1.0
 */
public final class CatalogDdlCompactor {
	private static final String CREATE_SCHEMA_PREFIX = "CREATE SCHEMA IF NOT EXISTS ";
	private static final String CREATE_TABLE_PREFIX = "CREATE TABLE IF NOT EXISTS ";
	private static final String CREATE_SEQUENCE_PREFIX = "CREATE SEQUENCE IF NOT EXISTS ";
	private static final String CREATE_VIEW_PREFIX = "CREATE VIEW ";
	private static final String CREATE_MAT_VIEW_PREFIX = "CREATE MATERIALIZED VIEW ";
	private static final String CREATE_INDEX = "CREATE INDEX ";
	private static final String CREATE_BITMAP_INDEX = "CREATE BITMAP INDEX ";
	private static final String ON_KW = " ON ";
	private static final String AS_KW = " AS ";
	private static final String NOT_NULL = " NOT NULL";
	private static final String IDENTITY = " GENERATED BY DEFAULT AS IDENTITY";
	private static final String START_WITH = " START WITH ";
	private static final String INCREMENT_BY = " INCREMENT BY ";
	private static final String RECLAIM = " RECLAIM";

	private CatalogDdlCompactor() {
	}

	/**
	 * Emit CREATE SCHEMA / TABLE / INDEX / SEQUENCE / VIEW lines for a restart-safe journal.
	 */
	public static List<String> compactLines(TableCatalog catalog) {
		final ArrayList<String> lines = new ArrayList<>();
		final Set<String> schemas = catalog.schemaNames();
		final ArrayList<String> named = new ArrayList<>();
		for (String schema : schemas) {
			if (!CatalogPersistUtil.SCHEMA_PUBLIC.equals(schema)) {
				named.add(schema);
			}
		}
		named.sort(Comparator.naturalOrder());
		for (String schema : named) {
			lines.add(CREATE_SCHEMA_PREFIX + schema);
		}
		final ArrayList<String> tables = new ArrayList<>(catalog.tableNames());
		tables.sort(Comparator.naturalOrder());
		for (String table : tables) {
			final TableSchema schema = catalog.getSchema(table);
			if (schema == null) {
				continue;
			}
			lines.add(renderCreateTable(schema));
			for (IndexDef idx : schema.indexes()) {
				lines.add(renderCreateIndex(table, idx));
			}
		}
		for (SequenceDef seq : catalog.sequenceDefs()) {
			if (seq.ownedByTableOrNull() != null && !seq.ownedByTableOrNull().isBlank()) {
				continue;
			}
			lines.add(renderCreateSequence(seq));
		}
		final ArrayList<String> views = new ArrayList<>(catalog.viewNames());
		views.sort(Comparator.naturalOrder());
		for (String viewName : views) {
			final TableCatalog.ViewDef view = catalog.getView(viewName);
			if (view == null) {
				continue;
			}
			final String prefix = view.materialized() ? CREATE_MAT_VIEW_PREFIX : CREATE_VIEW_PREFIX;
			lines.add(prefix + view.name() + AS_KW + view.selectSql());
		}
		return List.copyOf(lines);
	}

	private static String renderCreateTable(TableSchema schema) {
		final StringBuilder sb = new StringBuilder(CREATE_TABLE_PREFIX);
		sb.append(schema.tableName()).append(" (");
		boolean first = true;
		final ArrayList<String> tablePk = new ArrayList<>();
		for (ColumnDef col : schema.columns()) {
			if (!first) {
				sb.append(", ");
			}
			first = false;
			sb.append(col.name()).append(' ').append(col.type().name());
			if (col.identity()) {
				sb.append(IDENTITY);
			}
			if (!col.nullable() && !col.primaryKey()) {
				sb.append(NOT_NULL);
			}
			if (col.primaryKey()) {
				tablePk.add(col.name());
			}
		}
		if (!tablePk.isEmpty()) {
			sb.append(", PRIMARY KEY (");
			for (int i = 0; i < tablePk.size(); i++) {
				if (i > 0) {
					sb.append(", ");
				}
				sb.append(tablePk.get(i));
			}
			sb.append(')');
		}
		sb.append(')');
		return sb.toString();
	}

	private static String renderCreateIndex(String table, IndexDef idx) {
		final StringBuilder sb = new StringBuilder(
				idx.kind() == IndexType.BITMAP ? CREATE_BITMAP_INDEX : CREATE_INDEX);
		sb.append(idx.name()).append(ON_KW).append(table).append(" (");
		final List<String> cols = idx.columns();
		for (int i = 0; i < cols.size(); i++) {
			if (i > 0) {
				sb.append(", ");
			}
			sb.append(cols.get(i));
		}
		sb.append(')');
		return sb.toString();
	}

	private static String renderCreateSequence(SequenceDef seq) {
		final StringBuilder sb = new StringBuilder(CREATE_SEQUENCE_PREFIX);
		sb.append(seq.name())
				.append(START_WITH).append(seq.startValue())
				.append(INCREMENT_BY).append(seq.increment());
		if (seq.reclaim()) {
			sb.append(RECLAIM);
		}
		return sb.toString();
	}
}
