/*
 * Copyright 2024-2026 GenCloud
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package index.unit.catalog;

import org.genfork.grid.catalog.CatalogDdlCompactor;
import org.genfork.grid.catalog.SqlType;
import org.genfork.grid.catalog.TableCatalog;
import org.genfork.grid.catalog.TableSchema;
import org.genfork.grid.sql.SqlEngine;
import org.genfork.grid.sql.SqlStatementParser;
import org.genfork.grid.sql.ast.DdlAst.CreateTableSql;
import org.genfork.grid.sql.ast.Stmt;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Locale;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Compacted CREATE TABLE must emit NOT NULL before IDENTITY (grammar order);
 * legacy IDENTITY-before-NOT-NULL journal lines must still parse and recover.
 *
 * @author: GenCloud
 * @date: 2026/10
 * @since: 1.1
 */
public class CatalogDdlCompactorIdentityOrderTest {
	private static final String LEGACY_IDENTITY_NOT_NULL =
			"CREATE TABLE IF NOT EXISTS shared_game_server.olympiad_heroes_matches ("
					+ "id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "
					+ "player_id INT, server_id INT NOT NULL, "
					+ "PRIMARY KEY (id))";

	@TempDir
	Path tempDir;

	@Test
	void compactEmitsNotNullBeforeIdentity() {
		final TableCatalog catalog = new TableCatalog();
		catalog.createSchema("s", false);
		catalog.createTable(TableSchema.builder("s.t")
				.primaryKey("k", SqlType.INT)
				.identityColumn("id", SqlType.INT, false, "s.t_id_seq")
				.build());
		final List<String> lines = CatalogDdlCompactor.compactLines(catalog);
		final String create = lines.stream()
				.filter(l -> l.toLowerCase(Locale.ROOT).contains("create table"))
				.findFirst()
				.orElseThrow();
		final String lower = create.toLowerCase(Locale.ROOT);
		final int idCol = lower.indexOf("id int");
		final String idFragment = lower.substring(idCol, idCol + 64);
		final int notNullAt = idFragment.indexOf("not null");
		final int identityAt = idFragment.indexOf("generated by default as identity");
		assertTrue(notNullAt >= 0, create);
		assertTrue(identityAt >= 0, create);
		assertTrue(notNullAt < identityAt, create);
		assertFalse(lower.contains("identity not null"), create);
	}

	@Test
	void legacyIdentityNotNullParses() {
		final Stmt stmt = SqlStatementParser.parse(LEGACY_IDENTITY_NOT_NULL);
		assertInstanceOf(CreateTableSql.class, stmt);
		final CreateTableSql create = (CreateTableSql) stmt;
		assertTrue(create.columns().getFirst().identity());
		assertTrue(create.columns().getFirst().notNull());
	}

	@Test
	void recoverPersistedCatalogAcceptsLegacyIdentityNotNull() throws Exception {
		final Path dataDir = tempDir.resolve("id-nn");
		final Path catalogDir = dataDir.resolve("catalog");
		Files.createDirectories(catalogDir);
		Files.writeString(catalogDir.resolve("schemas.list"), "shared_game_server\n", StandardCharsets.UTF_8);
		Files.writeString(
				catalogDir.resolve("ddl.sql"),
				"CREATE SCHEMA IF NOT EXISTS shared_game_server\n"
						+ LEGACY_IDENTITY_NOT_NULL + "\n",
				StandardCharsets.UTF_8);
		final SqlEngine engine = new SqlEngine(new TableCatalog(dataDir), null, 4);
		engine.recoverPersistedCatalog();
		assertTrue(engine.catalog().exists("shared_game_server.olympiad_heroes_matches"));
	}
}
