/*
 * Copyright 2024-2026 GenCloud
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.genfork.grid.sql.ast;

import java.util.List;

import org.genfork.grid.mem.index.IndexType;

/**
 * DDL / schema / view / function / sequence AST types.
 *
 * @author: GenCloud
 * @date: 2025/11
 * @since: 1.0
 */
public final class DdlAst {
	private DdlAst() {
	}

	/**
	 * Parsed CHECK constraint.
	 *
	 * @author: GenCloud
	 * @date: 2025/11
	 * @since: 1.0
	 */
	public record CheckSpec(String nameOrNull, String expressionSql) {
	}

	/**
	 * {@code CREATE TABLE …}.
	 *
	 * @author: GenCloud
	 * @date: 2025/11
	 * @since: 1.0
	 */
	public record CreateTableSql(
			String table,
			boolean ifNotExists,
			List<ColumnSpec> columns,
			List<String> tablePk,
			List<FkSpec> foreignKeys,
			List<CheckSpec> checks
	) implements Stmt {
		public CreateTableSql(String table, boolean ifNotExists, List<ColumnSpec> columns, List<String> tablePk) {
			this(table, ifNotExists, columns, tablePk, List.of(), List.of());
		}
	}

	/**
	 * Column DDL fragment from ANTLR {@code columnDef}.
	 *
	 * @param identity {@code GENERATED BY DEFAULT AS IDENTITY} or {@code SERIAL}/{@code BIGSERIAL}
	 * @param serial   true when type was {@code SERIAL}/{@code BIGSERIAL} (implies identity)
	 *
	 * @author: GenCloud
	 * @date: 2025/11
	 * @since: 1.0
	 */
	public record ColumnSpec(
			String name,
			String typeToken,
			boolean notNull,
			boolean primaryKey,
			boolean identity,
			boolean serial
	) {
		public ColumnSpec(String name, String typeToken, boolean notNull, boolean primaryKey) {
			this(name, typeToken, notNull, primaryKey, false, false);
		}
	}

	/** Table-level {@code FOREIGN KEY … REFERENCES …} from ANTLR. */
	public record FkSpec(
			String nameOrNull,
			List<String> childColumns,
			String parentTable,
			List<String> parentColumns,
			String onDeleteOrNull,
			String onUpdateOrNull
	) {
	}

	/**
	 * {@code CREATE SEQUENCE …}.
	 *
	 * @author: GenCloud
	 * @date: 2025/11
	 * @since: 1.0
	 */
	public record CreateSequenceSql(
			String name,
			boolean ifNotExists,
			long startValue,
			long increment,
			boolean reclaim
	) implements Stmt {
	}

	/**
	 * {@code DROP SEQUENCE …}.
	 *
	 * @author: GenCloud
	 * @date: 2025/11
	 * @since: 1.0
	 */
	public record DropSequenceSql(String name, boolean ifExists) implements Stmt {
	}

	/**
	 * Standalone {@code SELECT nextval/currval(...)} (no FROM).
	 *
	 * @author: GenCloud
	 * @date: 2025/11
	 * @since: 1.0
	 */
	public record SequenceValueSql(boolean nextVal, String sequenceName) implements Stmt {
	}

	/**
	 * {@code DROP TABLE …}.
	 *
	 * @author: GenCloud
	 * @date: 2025/11
	 * @since: 1.0
	 */
	public record DropTableSql(String table, boolean ifExists) implements Stmt {
	}

	/**
	 * {@code CREATE [BITMAP|UNIQUE] INDEX …}.
	 *
	 * @author: GenCloud
	 * @date: 2025/11
	 * @since: 1.0
	 */
	public record CreateIndexSql(String indexName, String table, List<String> columns,
	                             IndexType kind) implements Stmt {
	}

	/**
	 * {@code DROP INDEX …}.
	 *
	 * @author: GenCloud
	 * @date: 2025/11
	 * @since: 1.0
	 */
	public record DropIndexSql(String indexName, String tableOrNull) implements Stmt {
	}

	/**
	 * {@code CREATE SCHEMA …}.
	 *
	 * @author: GenCloud
	 * @date: 2025/11
	 * @since: 1.0
	 */
	public record CreateSchemaSql(String schema, boolean ifNotExists) implements Stmt {
	}

	/**
	 * {@code DROP SCHEMA …}.
	 *
	 * @author: GenCloud
	 * @date: 2025/11
	 * @since: 1.0
	 */
	public record DropSchemaSql(String schema, boolean ifExists) implements Stmt {
	}

	/**
	 * {@code SET SCHEMA …}.
	 *
	 * @author: GenCloud
	 * @date: 2025/11
	 * @since: 1.0
	 */
	public record SetSchemaSql(String schema) implements Stmt {
	}

	/**
	 * Session-scoped opt-in for distributed dirty upsert visibility.
	 *
	 * @author: GenCloud
	 * @date: 2025/11
	 * @since: 1.0
	 */
	public record SetRemoteDirtySql(boolean enabled) implements Stmt {
	}

	/**
	 * Typed ALTER TABLE operation.
	 * {@code addColumn} null means DROP COLUMN {@code dropColumn}.
	 *
	 * @author: GenCloud
	 * @date: 2025/11
	 * @since: 1.0
	 */
	public record AlterTableSql(
			String table,
			ColumnSpec addColumn,
			String dropColumn,
			CheckSpec addCheck
	) implements Stmt {
		public AlterTableSql(String table, ColumnSpec addColumn, String dropColumn) {
			this(table, addColumn, dropColumn, null);
		}
	}

	/**
	 * {@code CREATE VIEW …}.
	 *
	 * @author: GenCloud
	 * @date: 2025/11
	 * @since: 1.0
	 */
	public record CreateViewSql(String table, String selectSql) implements Stmt {
	}

	/**
	 * {@code DROP VIEW …}.
	 *
	 * @author: GenCloud
	 * @date: 2025/11
	 * @since: 1.0
	 */
	public record DropViewSql(String table, boolean ifExists) implements Stmt {
	}

	/**
	 * {@code CREATE MATERIALIZED VIEW …}.
	 *
	 * @author: GenCloud
	 * @date: 2025/11
	 * @since: 1.0
	 */
	public record CreateMaterializedViewSql(String table, String selectSql) implements Stmt {
	}

	/**
	 * {@code REFRESH MATERIALIZED VIEW …}.
	 *
	 * @author: GenCloud
	 * @date: 2025/11
	 * @since: 1.0
	 */
	public record RefreshMaterializedViewSql(String table) implements Stmt {
	}

	/**
	 * {@code CREATE FUNCTION name(…) RETURNS type|TABLE AS CLASS '…' METHOD '…'}.
	 *
	 * @author: GenCloud
	 * @date: 2025/11
	 * @since: 1.0
	 */
	public record CreateFunctionSql(
			String name,
			List<String> paramNames,
			List<String> paramTypeTokens,
			String returnTypeToken,
			boolean returnsTable,
			List<String> tableColumnNames,
			List<String> tableColumnTypeTokens,
			String className,
			String methodName
	) implements Stmt {
		/** Scalar RETURNS type convenience. */
		public CreateFunctionSql(
				String name,
				List<String> paramNames,
				List<String> paramTypeTokens,
				String returnTypeToken,
				String className,
				String methodName
		) {
			this(name, paramNames, paramTypeTokens, returnTypeToken, false,
					List.of(), List.of(), className, methodName);
		}
	}

	/**
	 * {@code DROP FUNCTION …}.
	 *
	 * @author: GenCloud
	 * @date: 2025/11
	 * @since: 1.0
	 */
	public record DropFunctionSql(String name, boolean ifExists) implements Stmt {
	}

	/**
	 * {@code CREATE TRIGGER name BEFORE|AFTER INSERT|UPDATE|DELETE ON table
	 * FOR EACH ROW|STATEMENT [WHEN '…'] AS 'dml'}.
	 *
	 * @author: GenCloud
	 * @date: 2025/11
	 * @since: 1.0
	 */
	public record CreateTriggerSql(
			String name,
			String timingToken,
			String eventToken,
			String granularityToken,
			String table,
			String whenSqlOrNull,
			String bodySql
	) implements Stmt {
	}

	/**
	 * {@code DROP TRIGGER [IF EXISTS] name [ON table]}.
	 *
	 * @author: GenCloud
	 * @date: 2025/11
	 * @since: 1.0
	 */
	public record DropTriggerSql(String name, boolean ifExists, String tableOrNull) implements Stmt {
	}
}