/*
 * Copyright 2024-2026 GenCloud
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.genfork.grid.sql.exec;

import org.genfork.grid.mem.index.IndexType;
import org.genfork.grid.sql.ast.DdlAst.AlterTableSql;
import org.genfork.grid.sql.ast.DdlAst.ColumnSpec;
import org.genfork.grid.sql.ast.DdlAst.CheckSpec;
import org.genfork.grid.sql.ast.DdlAst.CreateIndexSql;
import org.genfork.grid.sql.ast.DdlAst.CreateSchemaSql;
import org.genfork.grid.sql.ast.DdlAst.CreateSequenceSql;
import org.genfork.grid.sql.ast.DdlAst.CreateTableSql;
import org.genfork.grid.sql.ast.DdlAst.DropIndexSql;
import org.genfork.grid.sql.ast.DdlAst.DropSchemaSql;
import org.genfork.grid.sql.ast.DdlAst.DropSequenceSql;
import org.genfork.grid.sql.ast.DdlAst.DropTableSql;
import org.genfork.grid.sql.ast.DdlAst.FkSpec;

import java.util.List;
import java.util.Locale;

/**
 * Rebuilds persist/replicate DDL text from ANTLR-typed {@code Stmt} records
 * with a schema-qualified table name (no string/regex rewrite of original SQL).
 *
 * @author: GenCloud
 * @date: 2025/11
 * @since: 1.0
 */
public final class SqlDdlRender {
	private SqlDdlRender() {
	}

	public static String createTable(CreateTableSql s, String resolvedTable) {
		final StringBuilder sb = new StringBuilder("CREATE TABLE ");
		if (s.ifNotExists()) {
			sb.append("IF NOT EXISTS ");
		}
		sb.append(resolvedTable).append(" (");
		boolean first = true;
		for (ColumnSpec col : s.columns()) {
			if (!first) {
				sb.append(", ");
			}
			first = false;
			if (col.serial()) {
				sb.append(col.name()).append(' ')
						.append("BIGINT".equalsIgnoreCase(col.typeToken()) ? "BIGSERIAL" : "SERIAL");
			} else {
				sb.append(col.name()).append(' ').append(col.typeToken().toUpperCase(Locale.ROOT));
				if (col.notNull()) {
					sb.append(" NOT NULL");
				}
			}
			if (col.primaryKey()) {
				sb.append(" PRIMARY KEY");
			}
			if (col.identity() && !col.serial()) {
				sb.append(" GENERATED BY DEFAULT AS IDENTITY");
			}
		}
		if (!s.tablePk().isEmpty()) {
			if (!first) {
				sb.append(", ");
			}
			sb.append("PRIMARY KEY (");
			appendCols(sb, s.tablePk());
			sb.append(')');
		}
		if (s.foreignKeys() != null) {
			for (FkSpec fk : s.foreignKeys()) {
				sb.append(", ");
				if (fk.nameOrNull() != null && !fk.nameOrNull().isBlank()) {
					sb.append("CONSTRAINT ").append(fk.nameOrNull()).append(' ');
				}
				sb.append("FOREIGN KEY (");
				appendCols(sb, fk.childColumns());
				sb.append(") REFERENCES ").append(fk.parentTable()).append(" (");
				appendCols(sb, fk.parentColumns());
				sb.append(')');
				if (fk.onDeleteOrNull() != null) {
					sb.append(" ON DELETE ").append(fk.onDeleteOrNull().toUpperCase(Locale.ROOT));
				}
				if (fk.onUpdateOrNull() != null) {
					sb.append(" ON UPDATE ").append(fk.onUpdateOrNull().toUpperCase(Locale.ROOT));
				}
			}
		}
		if (s.checks() != null) {
			for (CheckSpec check : s.checks()) {
				sb.append(", ");
				if (check.nameOrNull() != null && !check.nameOrNull().isBlank()) {
					sb.append("CONSTRAINT ").append(check.nameOrNull()).append(' ');
				}
				sb.append("CHECK (").append(check.expressionSql()).append(')');
			}
		}
		sb.append(')');
		return sb.toString();
	}

	public static String createSequence(CreateSequenceSql s, String resolvedName) {
		final StringBuilder sb = new StringBuilder("CREATE SEQUENCE ");
		if (s.ifNotExists()) {
			sb.append("IF NOT EXISTS ");
		}
		sb.append(resolvedName)
				.append(" START WITH ").append(s.startValue())
				.append(" INCREMENT BY ").append(s.increment());
		if (s.reclaim()) {
			sb.append(" RECLAIM");
		}
		return sb.toString();
	}

	public static String dropSequence(DropSequenceSql s, String resolvedName) {
		final StringBuilder sb = new StringBuilder("DROP SEQUENCE ");
		if (s.ifExists()) {
			sb.append("IF EXISTS ");
		}
		sb.append(resolvedName);
		return sb.toString();
	}

	private static void appendCols(StringBuilder sb, List<String> cols) {
		for (int i = 0; i < cols.size(); i++) {
			if (i > 0) {
				sb.append(", ");
			}
			sb.append(cols.get(i));
		}
	}

	public static String dropTable(DropTableSql s, String resolvedTable) {
		final StringBuilder sb = new StringBuilder("DROP TABLE ");
		if (s.ifExists()) {
			sb.append("IF EXISTS ");
		}
		sb.append(resolvedTable);
		return sb.toString();
	}

	public static String createIndex(CreateIndexSql s, String resolvedTable) {
		final StringBuilder sb = new StringBuilder("CREATE ");
		if (s.kind() == IndexType.BITMAP) {
			sb.append("BITMAP ");
		} else if (s.kind() == IndexType.STRICT) {
			sb.append("UNIQUE ");
		}
		sb.append("INDEX ").append(s.indexName()).append(" ON ").append(resolvedTable).append(" (");
		final List<String> cols = s.columns();
		for (int i = 0; i < cols.size(); i++) {
			if (i > 0) {
				sb.append(", ");
			}
			sb.append(cols.get(i));
		}
		sb.append(')');
		return sb.toString();
	}

	public static String dropIndex(DropIndexSql s, String resolvedTable) {
		final StringBuilder sb = new StringBuilder("DROP INDEX ").append(s.indexName());
		if (resolvedTable != null) {
			sb.append(" ON ").append(resolvedTable);
		}
		return sb.toString();
	}

	public static String createSchema(CreateSchemaSql s) {
		final StringBuilder sb = new StringBuilder("CREATE SCHEMA ");
		if (s.ifNotExists()) {
			sb.append("IF NOT EXISTS ");
		}
		sb.append(s.schema());
		return sb.toString();
	}

	public static String dropSchema(DropSchemaSql s) {
		final StringBuilder sb = new StringBuilder("DROP SCHEMA ");
		if (s.ifExists()) {
			sb.append("IF EXISTS ");
		}
		sb.append(s.schema()).append(" RESTRICT");
		return sb.toString();
	}

	public static String alterTable(AlterTableSql s, String resolvedTable) {
		final StringBuilder sb = new StringBuilder("ALTER TABLE ").append(resolvedTable).append(' ');
		if (s.addCheck() != null) {
			final CheckSpec check = s.addCheck();
			sb.append("ADD ");
			if (check.nameOrNull() != null && !check.nameOrNull().isBlank()) {
				sb.append("CONSTRAINT ").append(check.nameOrNull()).append(' ');
			}
			sb.append("CHECK (").append(check.expressionSql()).append(')');
		} else if (s.addColumn() != null) {
			final ColumnSpec col = s.addColumn();
			sb.append("ADD COLUMN ").append(col.name()).append(' ')
					.append(col.typeToken().toUpperCase(Locale.ROOT));
			if (col.notNull()) {
				sb.append(" NOT NULL");
			}
		} else {
			sb.append("DROP COLUMN ").append(s.dropColumn());
		}
		return sb.toString();
	}

	public static String createView(String resolvedTable, String selectSql) {
		return "CREATE VIEW " + resolvedTable + " AS " + selectSql;
	}

	public static String dropView(String resolvedTable, boolean ifExists) {
		final StringBuilder sb = new StringBuilder("DROP VIEW ");
		if (ifExists) {
			sb.append("IF EXISTS ");
		}
		sb.append(resolvedTable);
		return sb.toString();
	}

	public static String createMaterializedView(String resolvedTable, String selectSql) {
		return "CREATE MATERIALIZED VIEW " + resolvedTable + " AS " + selectSql;
	}

	public static String refreshMaterializedView(String resolvedTable) {
		return "REFRESH MATERIALIZED VIEW " + resolvedTable;
	}

	public static String createTrigger(
			String name,
			String timingToken,
			String eventToken,
			String granularityToken,
			String resolvedTable,
			String whenSqlOrNull,
			String bodySql
	) {
		final StringBuilder sb = new StringBuilder("CREATE TRIGGER ")
				.append(name).append(' ')
				.append(timingToken.toUpperCase(Locale.ROOT)).append(' ')
				.append(eventToken.toUpperCase(Locale.ROOT))
				.append(" ON ").append(resolvedTable)
				.append(" FOR EACH ")
				.append(granularityToken.toUpperCase(Locale.ROOT));
		if (whenSqlOrNull != null && !whenSqlOrNull.isBlank()) {
			sb.append(" WHEN ").append(quoteSqlString(whenSqlOrNull));
		}
		sb.append(" AS ").append(quoteSqlString(bodySql));
		return sb.toString();
	}

	public static String dropTrigger(String name, boolean ifExists, String resolvedTableOrNull) {
		final StringBuilder sb = new StringBuilder("DROP TRIGGER ");
		if (ifExists) {
			sb.append("IF EXISTS ");
		}
		sb.append(name);
		if (resolvedTableOrNull != null && !resolvedTableOrNull.isBlank()) {
			sb.append(" ON ").append(resolvedTableOrNull);
		}
		return sb.toString();
	}

	private static String quoteSqlString(String raw) {
		return "'" + raw.replace("'", "''") + "'";
	}
}